substitutions:
  name: espcontrol-jc1060p470-d07d48
  friendly_name: Espcontrol 7inch

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

packages:
  setup:
    url: https://github.com/jtenniswood/espcontrol/
    file: devices/guition-esp32-p4-jc1060p470/packages.yaml
    refresh: 1sec
